name: mskg/homey-heating
on:
  push:
    branches:
    - "**/*"
  pull_request:
concurrency:
#   # This item has no matching transformer
#   maximum_number_of_builds: 0
  group: "${{ github.ref }}"
  cancel-in-progress: true
env:
  GITHUB_OAUTH_TOKEN: "${{ secrets.GITHUB_OAUTH_TOKEN }}"
  SENTRY_ORG: "${{ secrets.SENTRY_ORG }}"
  SENTRY_PROJECT: "${{ secrets.SENTRY_PROJECT }}"
  SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
jobs:
  test:
    runs-on: # this agent type is not supported: [[{"dist"=>"trusty"}]]
             ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v3.6.0
      with:
        cache: npm
        node-version: 11
    - run: npm install
    - run: if [ ${{ github.ref }} != '' ]; then npm run travis:setversion ${{ github.ref }}; fi
    - run: npm install -g athom-cli
    - run: npm run test
    - run: npm run dist
#     # This item has no matching transformer
#     - pages:
#         provider: pages
#         github-token: "$GITHUB_OAUTH_TOKEN"
#         skip_cleanup: true
#         keep-history: false
#         target-branch: release/${{ github.ref }}
#         local-dir: "../homey-heating-dist"
#         'on':
#           tags: true
#       if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"
    - run: npm run travis:sentry -- releases files homey-heating@${TRAVIS_TAG:1} upload-sourcemaps ../homey-heating-dist --rewrite --ignore-file scripts/.sentryignore
      if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"
    - run: npm run travis:sentry -- releases set-commits homey-heating@${TRAVIS_TAG:1} --auto
      if: "${{ github.event_name == 'push' && ${{ github.ref }} }}"
